#line 2 "conf_scanner.cc"

#line 4 "conf_scanner.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer conf_create_buffer
#define yy_delete_buffer conf_delete_buffer
#define yy_flex_debug conf_flex_debug
#define yy_init_buffer conf_init_buffer
#define yy_flush_buffer conf_flush_buffer
#define yy_load_buffer_state conf_load_buffer_state
#define yy_switch_to_buffer conf_switch_to_buffer
#define yyin confin
#define yyleng confleng
#define yylex conflex
#define yylineno conflineno
#define yyout confout
#define yyrestart confrestart
#define yytext conftext
#define yywrap confwrap
#define yyalloc confalloc
#define yyrealloc confrealloc
#define yyfree conffree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE confrestart(confin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int confleng;

extern FILE *confin, *confout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up conftext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up conftext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via confrestart()), so that the user can continue scanning by
	 * just pointing confin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when conftext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int confleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow confwrap()'s to do buffer switches
 * instead of setting up a fresh confin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void confrestart (FILE *input_file  );
void conf_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE conf_create_buffer (FILE *file,int size  );
void conf_delete_buffer (YY_BUFFER_STATE b  );
void conf_flush_buffer (YY_BUFFER_STATE b  );
void confpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void confpop_buffer_state (void );

static void confensure_buffer_stack (void );
static void conf_load_buffer_state (void );
static void conf_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER conf_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE conf_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE conf_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE conf_scan_bytes (yyconst char *bytes,int len  );

void *confalloc (yy_size_t  );
void *confrealloc (void *,yy_size_t  );
void conffree (void *  );

#define yy_new_buffer conf_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        confensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            conf_create_buffer(confin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        confensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            conf_create_buffer(confin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define confwrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *confin = (FILE *) 0, *confout = (FILE *) 0;

typedef int yy_state_type;

extern int conflineno;

int conflineno = 1;

extern char *conftext;
#define yytext_ptr conftext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up conftext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	confleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 58
#define YY_END_OF_BUFFER 59
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[304] =
    {   0,
        0,    0,   52,   52,   59,   57,   49,   56,   57,   50,
        3,    4,   46,   57,   45,    7,   44,   14,   12,   13,
        5,    6,   44,   44,   44,   44,   44,   44,   13,   44,
       44,   44,   44,   44,   44,   44,    1,    2,   52,   54,
       53,   49,    0,   48,   50,   46,   51,   46,   45,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   23,   44,   44,   44,   44,   44,
       44,   44,   44,   52,   53,   53,   55,   46,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,    9,   44,   44,   44,   44,   44,   44,   44,   44,

       44,    0,   44,   44,   44,   44,   44,   44,   44,   10,
       44,   44,   44,   44,   44,   44,   19,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,    0,   44,   44,
        8,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   35,
       44,   44,    0,   44,   44,   44,   44,   15,   31,   21,
       44,   44,   16,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   47,   44,   44,   44,   30,
       44,   44,   44,   44,   27,   44,   44,   44,   44,   44,
       44,   44,   44,   24,   44,   44,   44,   44,   44,   11,

       26,   44,   44,   44,   44,   36,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   42,   44,   44,   44,   44,
       44,   17,   44,   44,   39,   44,   44,   44,   44,   44,
       18,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   33,   20,   44,   29,   25,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   22,   44,   44,   44,   28,
       44,   40,   43,   44,   44,   38,   44,   41,   44,   44,
       44,   32,   44,   44,   44,   44,   44,   44,   44,   34,

       44,   37,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    1,    1,    6,
        7,    8,    1,    1,    1,    9,   10,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,    1,   12,    1,
        1,    1,    1,    1,   13,   13,   13,   13,   13,   13,
       14,   13,   13,   13,   15,   13,   16,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       17,    1,   18,    1,   19,    1,   20,   21,   22,   23,

       24,   25,   26,   27,   28,   13,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       43,   44,   45,    1,   46,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[47] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    3,    1,    1,
        4,    1,    4,    4,    4,    4,    1,    1,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    1,    1
    } ;

static yyconst flex_int16_t yy_base[310] =
    {   0,
        0,    0,   44,   45,  597,  598,  594,  598,  591,    0,
      598,  598,  583,  585,   40,  598,  581,  580,  579,  578,
      598,  598,   39,   43,   44,   46,   45,   47,   59,   48,
       49,   50,   60,   75,   51,   55,  598,  598,    0,  598,
       55,  586,  583,  582,    0,  574,  598,  573,   58,  572,
      571,   79,   82,   83,   84,   85,   87,   88,   89,   90,
       93,   92,   95,   97,  570,   94,  102,  100,   99,   96,
      103,  118,  120,    0,  125,  130,  598,  130,  132,  133,
      134,  135,  136,  137,  143,  138,  139,  149,  150,  142,
      165,  569,  141,  168,  147,  151,  170,  172,  148,  144,

      174,  568,  175,  177,  180,  178,  181,  184,  185,  567,
      187,  189,  191,  190,  193,  199,  566,  201,  197,  198,
      202,  207,  209,  208,  212,  213,  220,  224,  219,  223,
      565,  226,  228,  229,  233,  235,  234,  238,  236,  237,
      242,  245,  244,  246,  250,  252,  256,  257,  258,  562,
      259,  260,  559,  266,  268,  271,  272,  558,  554,  550,
      275,  274,  543,  276,  278,  283,  280,  281,  286,  282,
      289,  290,  291,  297,  298,  542,  300,  301,  302,  541,
      311,  312,  304,  314,  540,  318,  330,  313,  310,  316,
      332,  333,  336,  539,  337,  339,  340,  343,  344,  538,

      537,  346,  320,  347,  349,  536,  352,  357,  348,  354,
      358,  362,  363,  364,  370,  372,  374,  373,  375,  379,
      376,  380,  378,  383,  387,  394,  385,  392,  395,  396,
      397,  535,  399,  403,  406,  407,  412,  418,  415,  421,
      534,  408,  411,  422,  425,  428,  430,  429,  431,  433,
      434,  436,  533,  532,  437,  531,  528,  441,  442,  439,
      452,  443,  444,  451,  447,  455,  462,  467,  469,  468,
      471,  473,  474,  477,  478,  527,  479,  481,  482,  526,
      483,  524,  523,  484,  487,  522,  485,  521,  486,  490,
      488,  520,  507,  489,  505,  516,  491,  517,  518,  492,

      519,  319,  598,  555,  559,  563,  113,  567,  571
    } ;

static yyconst flex_int16_t yy_def[310] =
    {   0,
      303,    1,  304,  304,  303,  303,  303,  303,  305,  306,
      303,  303,  303,  303,  303,  303,  307,  307,  307,  307,
      303,  303,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  303,  303,  308,  303,
      309,  303,  305,  305,  306,  303,  303,  303,  303,  303,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  308,  309,  309,  303,  303,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,

      307,  303,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  303,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  303,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  303,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,

      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,

      307,  307,    0,  303,  303,  303,  303,  303,  303
    } ;

static yyconst flex_int16_t yy_nxt[645] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,    6,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   22,   17,   17,
       23,   24,   25,   17,   26,   18,   17,   27,   19,   28,
       29,   30,   17,   31,   32,   33,   34,   35,   17,   17,
       36,   17,   17,   17,   37,   38,   40,   40,   48,   50,
       49,   41,   41,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   76,   56,   77,   50,   48,   57,   49,   50,
       50,   58,   53,   60,   52,   54,   61,   66,   63,   62,
       65,   55,   64,   69,   67,   50,   59,   73,   68,   50,
       70,   72,   50,   50,   50,   50,   71,   50,   50,   50,

       50,   80,   50,   50,   50,   50,   50,   50,   83,   50,
       50,   79,   50,   50,   81,   88,   51,   89,   97,   87,
       86,   82,   90,   96,   85,   94,   84,   92,   50,   95,
       50,   93,  303,   98,  303,   99,   91,   76,  102,   77,
       78,  100,   50,   50,   50,   50,   50,   50,   50,   50,
      103,   50,   50,   50,   50,  101,  111,   50,   50,   50,
       50,   50,  112,  126,  109,  105,  108,  107,  115,  104,
      106,  110,  114,  117,  116,   50,  113,  119,   50,  121,
       50,  125,   50,  118,   50,   50,  122,   50,   50,  120,
       50,   50,  123,  124,   50,   50,  129,   50,  132,   50,

       50,   50,  127,   50,  130,  134,  136,   50,   50,   50,
      133,   50,   50,  131,  139,  144,  135,   50,   50,   50,
      141,  145,   50,   50,  137,  138,  142,  148,  143,   50,
       50,  140,  153,   50,  128,  150,   50,  146,   50,   50,
      149,  151,  152,   50,   50,   50,   50,   50,   50,  147,
      155,  154,   50,  158,   50,   50,   50,  157,  160,  164,
       50,  161,   50,  156,  159,  162,   50,   50,   50,   50,
       50,  163,  169,  165,  166,  167,   50,  174,   50,  170,
      171,   50,   50,  168,   50,   50,   50,  175,   50,  173,
       50,   50,   50,   50,  172,  180,   50,  177,  179,   50,

       50,   50,  186,  183,  178,  181,  185,   50,   50,  188,
       50,   50,   50,  187,   50,  184,  190,  182,  193,  189,
       50,   50,   50,   50,   50,  191,   50,  192,   50,   50,
       50,  195,  198,  194,  199,  200,  196,  202,  197,  201,
       50,  203,   50,   50,  205,  207,   50,   50,  204,   50,
       50,  208,  206,   50,   50,  210,   50,   50,   50,   50,
      211,  217,   50,  213,   50,  209,  214,   50,   50,  218,
      219,  212,   50,   50,   50,  220,  215,  222,  221,  224,
       50,  216,   50,   50,   50,   50,   50,  223,   50,   50,
       50,  225,  230,   50,  226,   50,  227,   50,  232,  234,

      231,  233,   50,  235,   50,   50,   50,   50,  228,   50,
      238,  229,  239,   50,  242,  236,   50,   50,   50,  243,
      237,   50,   50,  240,  247,   50,  245,  246,   50,  241,
      249,   50,   50,  244,  251,   50,  250,  254,   50,   50,
       50,   50,  255,   50,   50,  248,   50,   50,  252,   50,
      256,   50,   50,   50,   50,  258,  264,   50,  253,  259,
      257,   50,   50,  260,  261,   50,  263,  262,  265,  268,
      267,  269,   50,  273,  266,  270,  272,   50,   50,   50,
      271,   50,  274,   50,   50,  276,  279,   50,   50,   50,
      275,   50,   50,   50,   50,   50,   50,   50,   50,   50,

       50,   50,   50,  277,  278,  284,  280,  289,  281,  282,
      290,  291,  296,  299,  283,   50,  285,   50,  286,  287,
      288,  293,  292,  294,  297,  295,   50,   50,   50,   50,
       50,   50,   50,   50,   50,  298,   50,   50,   50,  300,
      301,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,  176,   50,  302,   39,   39,   39,   39,   43,
       50,   43,   43,   45,   50,   45,   45,   74,   50,  176,
       74,   75,   50,   75,   75,   50,   50,   50,  128,   50,
       50,   50,   50,   78,   46,   44,   44,   42,   50,   50,
       50,   50,   47,   46,   44,   42,  303,    5,  303,  303,

      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303
    } ;

static yyconst flex_int16_t yy_chk[645] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    4,   15,   23,
       15,    3,    4,   24,   25,   27,   26,   28,   30,   31,
       32,   35,   41,   25,   41,   36,   49,   25,   49,   29,
       33,   25,   24,   26,   23,   24,   27,   31,   29,   28,
       30,   24,   29,   33,   31,   34,   25,   36,   32,   52,
       33,   35,   53,   54,   55,   56,   34,   57,   58,   59,

       60,   53,   62,   61,   66,   63,   70,   64,   56,   69,
       68,   52,   67,   71,   54,   61,  307,   62,   69,   60,
       59,   55,   63,   68,   58,   67,   57,   64,   72,   67,
       73,   66,   75,   70,   75,   71,   63,   76,   78,   76,
       78,   72,   79,   80,   81,   82,   83,   84,   86,   87,
       79,   93,   90,   85,  100,   73,   86,   95,   99,   88,
       89,   96,   87,  100,   84,   81,   83,   82,   89,   80,
       81,   85,   88,   90,   89,   91,   87,   93,   94,   95,
       97,   99,   98,   91,  101,  103,   96,  104,  106,   94,
      105,  107,   97,   98,  108,  109,  103,  111,  105,  112,

      114,  113,  101,  115,  103,  107,  109,  119,  120,  116,
      106,  118,  121,  104,  113,  119,  108,  122,  124,  123,
      115,  120,  125,  126,  111,  112,  116,  123,  118,  129,
      127,  114,  128,  130,  128,  125,  132,  121,  133,  134,
      124,  126,  127,  135,  137,  136,  139,  140,  138,  122,
      130,  129,  141,  134,  143,  142,  144,  133,  136,  140,
      145,  137,  146,  132,  135,  138,  147,  148,  149,  151,
      152,  139,  145,  141,  142,  143,  154,  151,  155,  146,
      147,  156,  157,  144,  162,  161,  164,  152,  165,  149,
      167,  168,  170,  166,  148,  157,  169,  154,  156,  171,

      172,  173,  167,  164,  155,  161,  166,  174,  175,  169,
      177,  178,  179,  168,  183,  165,  171,  162,  174,  170,
      189,  181,  182,  188,  184,  172,  190,  173,  186,  302,
      203,  177,  179,  175,  181,  182,  177,  184,  178,  183,
      187,  186,  191,  192,  188,  190,  193,  195,  187,  196,
      197,  191,  189,  198,  199,  193,  202,  204,  209,  205,
      195,  203,  207,  197,  210,  192,  198,  208,  211,  204,
      205,  196,  212,  213,  214,  207,  199,  209,  208,  211,
      215,  202,  216,  218,  217,  219,  221,  210,  223,  220,
      222,  212,  217,  224,  213,  227,  214,  225,  219,  221,

      218,  220,  228,  222,  226,  229,  230,  231,  215,  233,
      225,  216,  226,  234,  229,  223,  235,  236,  242,  230,
      224,  243,  237,  227,  235,  239,  233,  234,  238,  228,
      237,  240,  244,  231,  239,  245,  238,  242,  246,  248,
      247,  249,  243,  250,  251,  236,  252,  255,  239,  260,
      244,  258,  259,  262,  263,  246,  251,  265,  240,  247,
      245,  264,  261,  247,  248,  266,  250,  249,  252,  259,
      258,  260,  267,  264,  255,  261,  263,  268,  270,  269,
      262,  271,  265,  272,  273,  267,  270,  274,  275,  277,
      266,  278,  279,  281,  284,  287,  289,  285,  291,  294,

      290,  297,  300,  268,  269,  275,  271,  284,  272,  273,
      285,  287,  294,  297,  274,  295,  277,  293,  278,  279,
      281,  290,  289,  291,  295,  293,  296,  298,  299,  301,
      292,  288,  286,  283,  282,  296,  280,  276,  257,  298,
      299,  256,  254,  253,  241,  232,  206,  201,  200,  194,
      185,  180,  176,  163,  301,  304,  304,  304,  304,  305,
      160,  305,  305,  306,  159,  306,  306,  308,  158,  153,
      308,  309,  150,  309,  309,  131,  117,  110,  102,   92,
       65,   51,   50,   48,   46,   44,   43,   42,   20,   19,
       18,   17,   14,   13,    9,    7,    5,  303,  303,  303,

      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int conf_flex_debug;
int conf_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *conftext;
#line 1 "conf_scanner.ll"
/*
Timemachine
Copyright (c) 2006 Technische Universitaet Muenchen,
                   Technische Universitaet Berlin,
                   The Regents of the University of California
All rights reserved.


Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

1. Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.
3. Neither the names of the copyright owners nor the names of its
   contributors may be used to endorse or promote products derived from
   this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED
WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
/* conf_scanner.ll       (emacs mode for this is --*-indented-text-*--)
 * $Id: conf_scanner.ll 253 2009-02-04 10:32:17Z gregor $
 *
 * Lex configuration file.
 */
/* autotools ylwrap seems to like this filename */
#line 51 "conf_scanner.ll"

  #include <string.h>
  #include <sys/socket.h>
  #include <netinet/in.h>
  #include <arpa/inet.h>
  #include "Fifo.hh"
  #include "conf_parser.h"
  void conferror(const char*);
  extern int conf_parse_lineno;



#line 776 "conf_scanner.cc"

#define INITIAL 0
#define comment 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int conflex_destroy (void );

int confget_debug (void );

void confset_debug (int debug_flag  );

YY_EXTRA_TYPE confget_extra (void );

void confset_extra (YY_EXTRA_TYPE user_defined  );

FILE *confget_in (void );

void confset_in  (FILE * in_str  );

FILE *confget_out (void );

void confset_out  (FILE * out_str  );

int confget_leng (void );

char *confget_text (void );

int confget_lineno (void );

void confset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int confwrap (void );
#else
extern int confwrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( conftext, confleng, 1, confout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( confin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( confin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, confin))==0 && ferror(confin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(confin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int conflex (void);

#define YY_DECL int conflex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after conftext and confleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 74 "conf_scanner.ll"

#line 964 "conf_scanner.cc"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! confin )
			confin = stdin;

		if ( ! confout )
			confout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			confensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				conf_create_buffer(confin,YY_BUF_SIZE );
		}

		conf_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of conftext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 304 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 598 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 75 "conf_scanner.ll"
return LBRACE;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 76 "conf_scanner.ll"
return RBRACE;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 77 "conf_scanner.ll"
return LPAREN;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 78 "conf_scanner.ll"
return RPAREN;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 79 "conf_scanner.ll"
return LBRACK;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 80 "conf_scanner.ll"
return RBRACK;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 81 "conf_scanner.ll"
return SEMICOLON;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 82 "conf_scanner.ll"
return TOK_CLASS;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 83 "conf_scanner.ll"
return TOK_MEM;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 84 "conf_scanner.ll"
return TOK_DISK;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 85 "conf_scanner.ll"
return TOK_FILESIZE;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 86 "conf_scanner.ll"
return TOK_K;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 87 "conf_scanner.ll"
return TOK_M;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 88 "conf_scanner.ll"
return TOK_G;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 89 "conf_scanner.ll"
return TOK_CUTOFF;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 90 "conf_scanner.ll"
return TOK_FILTER;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 91 "conf_scanner.ll"
return TOK_PRECEDENCE;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 92 "conf_scanner.ll"
return TOK_DYN_TIMEOUT;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 93 "conf_scanner.ll"
return TOK_MAIN;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 94 "conf_scanner.ll"
return TOK_LOG_INTERVAL;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 95 "conf_scanner.ll"
return TOK_DEVICE;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 96 "conf_scanner.ll"
return TOK_READ_TRACEFILE;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 97 "conf_scanner.ll"
return TOK_NO;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 98 "conf_scanner.ll"
return TOK_WORKDIR;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 99 "conf_scanner.ll"
return TOK_QUERYFILEDIR;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 100 "conf_scanner.ll"
return TOK_INDEXDIR;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 101 "conf_scanner.ll"
return TOK_LOGFILE;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 102 "conf_scanner.ll"
return TOK_BRO_CONNECT_STR;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 103 "conf_scanner.ll"
return TOK_PKTS_TO_DISK;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 104 "conf_scanner.ll"
return TOK_CONSOLE;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 105 "conf_scanner.ll"
return TOK_DAEMON;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 106 "conf_scanner.ll"
return TOK_MAX_INDEX_ENTRIES;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 107 "conf_scanner.ll"
return TOK_CONN_TIMEOUT;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 108 "conf_scanner.ll"
return TOK_TWEAK_CAPTURE_THREAD;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 109 "conf_scanner.ll"
return TOK_SCOPE;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 110 "conf_scanner.ll"
return TOK_PRIORITY;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 112 "conf_scanner.ll"
return TOK_RMTCONSOLE_LISTEN_ADDR;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 113 "conf_scanner.ll"
return TOK_RMTCONSOLE_PORT;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 114 "conf_scanner.ll"
return TOK_RMTCONSOLE;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 115 "conf_scanner.ll"
return TOK_BRO_LISTEN_ADDR;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 116 "conf_scanner.ll"
return TOK_BRO_LISTEN_PORT;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 117 "conf_scanner.ll"
return TOK_BRO_LISTEN;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 120 "conf_scanner.ll"
return TOK_BRO_LISTEN_PORT;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 123 "conf_scanner.ll"
{ conflval.s=strdup(conftext); return TOK_ID; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 124 "conf_scanner.ll"
{ conflval.i64=atol(conftext); return TOK_INTEGER; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 125 "conf_scanner.ll"
{ conflval.d=strtod(conftext, NULL); return TOK_DOUBLE; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 126 "conf_scanner.ll"
{
				if (!inet_aton(conftext, &(conflval.ipaddr)))
					conferror("Invald IP address");
				return TOK_IPADDRESS;
			}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 131 "conf_scanner.ll"
{ conflval.s=strdup(conftext+1);
		   conflval.s[strlen(conflval.s)-1]=0;
		   return TOK_STRING;
		 } 
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 135 "conf_scanner.ll"

	YY_BREAK
case 50:
YY_RULE_SETUP
#line 136 "conf_scanner.ll"

	YY_BREAK
case 51:
YY_RULE_SETUP
#line 137 "conf_scanner.ll"
BEGIN(comment);
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 138 "conf_scanner.ll"
/* eat anything that's not a '*' */
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 139 "conf_scanner.ll"
/* eat up '*'s not followed by '/'s */
	YY_BREAK
case 54:
/* rule 54 can match eol */
YY_RULE_SETUP
#line 140 "conf_scanner.ll"
++conf_parse_lineno;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 141 "conf_scanner.ll"
BEGIN(INITIAL);
	YY_BREAK
case 56:
/* rule 56 can match eol */
YY_RULE_SETUP
#line 142 "conf_scanner.ll"
{ conf_parse_lineno++; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 143 "conf_scanner.ll"
conferror("Illegal character in configuration file");
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 145 "conf_scanner.ll"
ECHO;
	YY_BREAK
#line 1346 "conf_scanner.cc"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(comment):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed confin at a new source and called
			 * conflex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = confin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( confwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * conftext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of conflex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					confrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			confrestart(confin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) confrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 304 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 304 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 303);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					confrestart(confin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( confwrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve conftext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void confrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        confensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            conf_create_buffer(confin,YY_BUF_SIZE );
	}

	conf_init_buffer(YY_CURRENT_BUFFER,input_file );
	conf_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void conf_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		confpop_buffer_state();
	 *		confpush_buffer_state(new_buffer);
     */
	confensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	conf_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (confwrap()) processing, but the only time this flag
	 * is looked at is after confwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void conf_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	confin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE conf_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) confalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in conf_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) confalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in conf_create_buffer()" );

	b->yy_is_our_buffer = 1;

	conf_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with conf_create_buffer()
 * 
 */
    void conf_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		conffree((void *) b->yy_ch_buf  );

	conffree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a confrestart() or at EOF.
 */
    static void conf_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	conf_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then conf_init_buffer was _probably_
     * called from confrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void conf_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		conf_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void confpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	confensure_buffer_stack();

	/* This block is copied from conf_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from conf_switch_to_buffer. */
	conf_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void confpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	conf_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		conf_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void confensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)confalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in confensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)confrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in confensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE conf_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) confalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in conf_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	conf_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to conflex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       conf_scan_bytes() instead.
 */
YY_BUFFER_STATE conf_scan_string (yyconst char * yystr )
{
    
	return conf_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to conflex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE conf_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) confalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in conf_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = conf_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in conf_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up conftext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		conftext[confleng] = (yy_hold_char); \
		(yy_c_buf_p) = conftext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		confleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int confget_lineno  (void)
{
        
    return conflineno;
}

/** Get the input stream.
 * 
 */
FILE *confget_in  (void)
{
        return confin;
}

/** Get the output stream.
 * 
 */
FILE *confget_out  (void)
{
        return confout;
}

/** Get the length of the current token.
 * 
 */
int confget_leng  (void)
{
        return confleng;
}

/** Get the current token.
 * 
 */

char *confget_text  (void)
{
        return conftext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void confset_lineno (int  line_number )
{
    
    conflineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see conf_switch_to_buffer
 */
void confset_in (FILE *  in_str )
{
        confin = in_str ;
}

void confset_out (FILE *  out_str )
{
        confout = out_str ;
}

int confget_debug  (void)
{
        return conf_flex_debug;
}

void confset_debug (int  bdebug )
{
        conf_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from conflex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    confin = stdin;
    confout = stdout;
#else
    confin = (FILE *) 0;
    confout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * conflex_init()
     */
    return 0;
}

/* conflex_destroy is for both reentrant and non-reentrant scanners. */
int conflex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		conf_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		confpop_buffer_state();
	}

	/* Destroy the stack itself. */
	conffree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * conflex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *confalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *confrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void conffree (void * ptr )
{
	free( (char *) ptr );	/* see confrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 145 "conf_scanner.ll"




